comprador/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import PedidoView, ListagemView, PedidoView, CompradorCreateView, EstoqueCreateView, HomeView, PedidoUpdateEstoque, LitarPedidoCliente, LitarFornecedoresP, PedidoUpdateView
from .views import PedidoUpdatePPView

app_name = 'comprador'
urlpatterns = [
    path('pedido/', PedidoView.as_view(), name='p'),
    #path('pedido/', PedidoView.as_view(), name='p'),
    path('listagem/', ListagemView.as_view(), name='list'),
    path('comprador_cadastro/', CompradorCreateView.as_view(), name='create_comprador'),
    path('estoque_compredor/', EstoqueCreateView.as_view(), name='create_estoque'),
    path('home_compredor/', HomeView.as_view(), name='comprador_home'),
    path('receber_pedido/', PedidoUpdateEstoque.as_view(), name='comprador_listar_pedidos'),
    path('lista_pedido_comprador/', LitarPedidoCliente.as_view(), name='comprador_pedido_list'),
    path('litar_fornecedores_p/', LitarFornecedoresP.as_view(), name='litar_fornecedores_p'),

    path('finalizar_pedido/<int:pk>/', PedidoUpdateView.as_view(), name='finalizar_pedido_up'),
    path('chegou_pedido/<int:pk>/', PedidoUpdatePPView.as_view(), name='uppp')
]

distribuidor/urls.py
from django.conf.urls import url
from django.contrib import admin
from django.urls import include, path
from .views import distribuidorCreateView,ListagemView,HomeView
from .views import EstoqueCreateView, EstoqueListView,ListagemCompradoresView,DetalheCompradoresListView
app_name = 'distribuidor'
urlpatterns = [
    path('home/', HomeView.as_view(), name='distribuidor_home'),
    path('cadastrar/', distribuidorCreateView.as_view(), name='distribuidor_create'),
    path('listar/', ListagemView.as_view(), name='distribuidor_list'),
    path('cadastrar_estoque/', EstoqueCreateView.as_view(), name='estoque_create'),
    path('listar_estoque/', EstoqueListView.as_view(), name='estoque_list'),
    path('listar_compradores/', ListagemCompradoresView.as_view(), name='listagem_compradores_list'),
    path('detalhe_compradores_listar/', DetalheCompradoresListView.as_view(), name='distribuidor_detail'),
]

maratona_ambev/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('siteprincipal.urls')),
    path('comprador/', include('comprador.urls')),
    path('distribuidor/', include('distribuidor.urls')),

]
#urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

matatona_ambev/matatona_ambev/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('siteprincipal.urls')),
    path('comprador/', include('comprador.urls')),

]
#urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

distribuidor/models.py
from django.db import models
import os
from django.utils.translation import ugettext_lazy as _
#from brutils import cpf as valida_cpf, cnpj as valida_cnpj

from django.urls import reverse
# Create your models here.
class Distribuidor(models.Model):
    nome_distribuidor = models.CharField(max_length=30)
    lat = models.DecimalField(max_digits=8, decimal_places=6, verbose_name= 'Latitude')
    lon = models.DecimalField(max_digits=8, decimal_places=6, verbose_name= 'Longitude')
    tel_fixo = models.CharField(_('Telefone Fixo'), max_length=13, blank=True, null=True)
    tel_celular = models.CharField(_('Telefone Celular'), max_length=13, blank=True, null=True)
    cep = models.CharField(_('CEP'), max_length=10, blank=True, null=True)
    uf = models.CharField(_('UF'), max_length=2, blank=True, null=True)
    cidade = models.CharField(_('Cidade'), max_length=70, blank=True, null=True)
    bairro = models.CharField(_('Bairro'), max_length=70, blank=True, null=True)
    logradouro = models.CharField(_('Logradouro'), max_length=70, blank=True, null=True)
    numero = models.CharField(_('Número'), max_length=5, blank=True, null=True)
    complemento = models.CharField(_('Complemento'), max_length=70, blank=True, null=True)
    dt_cadastro = models.DateTimeField(_('Dt. Cadastro'), auto_now_add=True)
    email = models.EmailField(_('E-mail'), blank=True, null=True)
    
    inicio_hora_entrega = models.TimeField(_('Inicio Periodo Entrada'),auto_now=False, auto_now_add=False,blank=True,
    null=True)
    fim_hora_entrega = models.TimeField(_('Fim Periodo Entrada'),auto_now=False, auto_now_add=False,blank=True,
    null=True)
    def __str__(self):
        return self.nome_distribuidor
    

class EstoqueDistribuidor(models.Model):
    distribuidor = models.ForeignKey(Distribuidor,on_delete=models.PROTECT)
    nome_produto = models.CharField(max_length=30) 
    quantidade_em_estoque = models.IntegerField(blank=True, null=True)

    @property
    def get_absolute_url2(self):
        return reverse('comprador:finalizar_pedido_up', kwargs={'pk': self.pk})

    def save(self, *args, **kwargs):
            
        super(EstoqueDistribuidor, self).save(*args, **kwargs)

    def __str__(self):
        return self.nome_produto
    

distribuidor/views.py
from django.urls import path
from django.views.generic import ListView, TemplateView, DetailView, RedirectView
from django.views.generic.edit import CreateView, UpdateView, DeleteView
from django.shortcuts import redirect
from django.contrib.auth import login
from django.contrib import messages
from django.urls import reverse
from django.conf import settings

from .models import Distribuidor, EstoqueDistribuidor
from comprador.models import Pedido

class HomeView(TemplateView):
    template_name = 'distribuidor_home.html'

class distribuidorCreateView(CreateView):
    model = Distribuidor
    template_name = "distribuidor_form.html"
    fields = ['fim_hora_entrega','inicio_hora_entrega','nome_distribuidor', 'email', 'tel_fixo','tel_celular','cep','cidade','lat','lon']
    success_url = 'landpage:home'

    def get_success_url(self):
        return reverse(self.success_url)

class EstoqueCreateView(CreateView):
    model = EstoqueDistribuidor
    template_name = "estoque_form.html"
    fields = ['distribuidor', 'nome_produto', 'quantidade_em_estoque']
    success_url = 'distribuidor:distribuidor_home'

    def get_initial(self):
        distribuidor = Distribuidor.objects.get(pk=4)

        return {'distribuidor': distribuidor}


    def get_success_url(self):
        return reverse(self.success_url)

class EstoqueListView(CreateView):
    template_name = "estoque_list.html"


class PedidoView(TemplateView):
    template_name = "pedido.html"


class ListagemView(TemplateView):
    template_name = "distribuidor_list.html"

class ListagemCompradoresView(ListView):
    model = Pedido
    template_name = "distribuidor_compradores_list.html"


    #filtrar pelo usuario logado    
    # def get_queryset(self):
    #     queryset = super(SubmissaoListView, self).get_queryset()
    #     queryset = queryset.filter(responsavel = self.request.user)
    #     return queryset
    def get_queryset(self):
        queryset = super(ListagemCompradoresView, self).get_queryset()
        queryset = queryset.filter(distribuidor__id=4)
        return queryset

class DetalheCompradoresListView(ListView):
    model = Distribuidor
    template_name = "estoque_fornecedor_list.html"


    def get_queryset(self):
            estoque_distri = EstoqueDistribuidor.objects.filter(distribuidor__id=4)
            # #self.request.session['quantidade_pedido'] = qual_quantidade_de_unidade
            # #self.request.session['nome_pedido'] = qual_seu_pedido
            # for i in estoque_distri:
            #     print(i.distribuidor)

            
            #palavra_chave = form.cleaned_data['palavra_chave']
            #tipo = form.cleaned_data['tipo']
            #situacao = form.cleaned_data['situacao']
            #categoria = form.cleaned_data['categoria']
            if self.request.GET:
                qs = super(DetalheCompradoresListView, self).get_queryset().filter(id=4)
                t = estoque_distri
            else:
                qs = super(DetalheCompradoresListView, self).get_queryset().filter(id=4)
                t = estoque_distri
            return t

    # def get_object(self, queryset=None):
    #     slug = self.kwargs.get(self.slug_url_kwarg)
    #     try:
    #         obj = EstoqueDistribuidor.objects.get(pk=4)
    #     except:
    #         print("!");
    #     return obj

    # #filtrar pelo usuario logado    
    # # def get_queryset(self):
    # #     queryset = super(SubmissaoListView, self).get_queryset()
    # #     queryset = queryset.filter(responsavel = self.request.user)
    # #     return queryset
    

distribuidor/templates/distribuidor_compradores_list.html
{% load static %}
{% extends 'core/layoutbase.html' %} 

{% block actions %}
{% endblock %}

{% block title %}
	Listagem de clientes do fornecedor x
  
{% endblock %}

{% block content %}

<table class="table">
    
  <thead>
    <tr>
        <td>ID pedido</td>
        <td>Comprador</td>
        <td>Distribuidor</td>
        <td>Pedido</td>
        <td>Localizar comprador</td>
        <td>Data da entrega</td>
        <td>Entrega</td>
    </tr>
  </thead>
  {% for i in object_list %}
  <tbody>
    <tr>
        <td><p>{{ i.pk }}</p></td>  
        <td>{{ i.comprador.nome_comprador }}</td>
        <td>{{ i.distribuidor.nome_distribuidor }}</td>
        <td>{{ i.qual_seu_pedido }}</td>    
        <td><a class="btn btn-primary" type="submit" href="http://127.0.0.1:8000/comprador/listagem/" role="button"></a></td>
        <td>{{ i.data_entrega|default_if_none:"Não entregue" }}</td>
        <td> {% if not i.entregue %}
            Não entregue
            {% else %}
                Entregue
            {% endif %}
        </td>   
    </tr>

  </tbody>
      {% endfor %}
</table>

{% endblock %}

distribuidor/templates/distribuidor_form.html
{% load static %}
{% extends 'core/layoutbase.html' %} 

{% block actions %}
{% endblock %}

{% block title %}
	Cadastro de fornecedor
{% endblock %}

{% block content %}
<div class="container">
        <h1>Tela cadastro fornecedor</h1>
        
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input  class="btn btn-primary" type="submit" value="cadastrar">
            {% comment %} <a class="btn btn-primary" type="submit" href="{% url 'comprador:list' %}" role="button"></a> {% endcomment %}
        </form>
        
    </div>
{% endblock %}

distribuidor/templates/distribuidor_home.html
{% load static %}
{% extends 'layoutbase.html' %} 


{% block content  %}

    <div class="container">
        <h1>Tela do distribuidor</h1>
        <a class="btn btn-primary" href="{% url 'distribuidor:distribuidor_create' %}" role="button">Cadastrar Fornecedor</a>
        <a class="btn btn-primary" href="{% url 'distribuidor:estoque_create' %}" role="button">criar estoque</a>
        <a class="btn btn-primary" href="{% url 'distribuidor:listagem_compradores_list' %}" role="button">listar compradores</a>
        <a class="btn btn-primary" href="{% url 'distribuidor:distribuidor_detail' %}" role="button">Distribuidor Estoque</a>
        

    </div>
{% endblock  %}

distribuidor/templates/estoque_form.html
{% load static %}
{% extends 'layoutbase.html' %} 

{% block actions %}
{% endblock %}

{% block title %}
	Cadastro do estoque
{% endblock %}

{% block content %}
<div class="container">
        <h1>Tela cadastro do estoque</h1>
        
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input  class="btn btn-primary" type="submit" value="cadastrar">
            {% comment %} <a class="btn btn-primary" type="submit" href="{% url 'comprador:list' %}" role="button"></a> {% endcomment %}
        </form>
        
    </div>
{% endblock %}

distribuidor/templates/estoque_fornecedor_list.html
{% load static %}
{% extends 'core/layoutbase.html' %} 

{% block actions %}
{% endblock %}

{% block title %}
	Listagem Estoque do fornecedor
  
{% endblock %}

{% block content %}

<table class="table">
    
  <thead>
    <tr>
        <td>Nome do Distribuidor</td>
        <td>Nome Do Produto</td>
        <td>Quantidade em Estoque</td>
    </tr>
  </thead>
  {% for i in object_list %}
  <tbody>
    <tr>
        <td>{{ i.distribuidor }}</td>
        <td>{{ i.nome_produto }}</td>
        <td>{{ i.quantidade_em_estoque }}</td>
        
    </tr>

  </tbody>
      {% endfor %}
</table>

{% endblock %}

distribuidor/templates/estoque_list.html
{% load static %}
{% extends 'layoutbase.html' %}

{% block title %}
	{% 'list-alt' %} Estoque
{% endblock %}

{% block content %}
	<div class="panel panel-default">
	  <div class="panel-body">
	    <a href="{% url 'distribuidor:estoque_create' %}" class="btn btn-md btn-primary"> Criar um novo produto</a>
	  </div>
	</div>
	<div class="table-responsive">
		<table class="table table-hover">
	  		<thead>
				<th>Distribuidor</th>
				<th>Produto</th>
				<th>Quantidade</th>	  			
	  		</thead>
	  		<tbody>
				{% for estoque in object_list %}
				<tr>
					<td>{{ estoque.distribuidor }}</td>
					<td>
						{% if estoque.nome_produto %}
							{{ estoque.nome_produto }}
						{% endif %}
					</td>

					<td>
						{% if estoque.quantidade_em_estoque %}
							{{ estoque.quantidade_em_estoque }}
						{% endif %}
					</td>

				</tr>
			    {% endfor %}
	  		</tbody>
		</table>
	</div>
{% endblock %}

distribuidor/templates/layoutbase.html
{% load static %}
<!doctype html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>Pricing example for Bootstrap</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/4.0/examples/pricing/">

    <!-- Bootstrap core CSS -->
    <link href="{% static 'bootstrap/css/bootstrap.min.css ' %}" rel="stylesheet">
<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
    <!-- Custom styles for this template -->
    <link href="pricing.css" rel="stylesheet">
  </head>

  <body>

    <div class="d-flex flex-column flex-md-row align-items-center p-3 px-md-4 mb-3 bg-white border-bottom box-shadow">
      <h5 class="my-0 mr-md-auto font-weight-normal">Ambev</h5>
      <nav class="my-2 my-md-0 mr-md-3">
      </nav>
      <a class="btn btn-outline-primary" href="#">Cadastre-se</a>
    </div>

    <div class="pricing-header px-3 py-3 pt-md-5 pb-md-4 mx-auto text-center">
      <h1 class="display-4">Principal</h1>
     
      {% block content %}
      {% endblock %}
    
    </div>

    <div class="container">




    <div class="container">
      <footer class="pt-4 my-md-5 pt-md-5 border-top">
        <div class="row">
          <div class="col-12 col-md">
            <img class="mb-2" src="https://getbootstrap.com/docs/4.0/assets/brand/bootstrap-solid.svg" alt="" width="24" height="24">
            <small class="d-block mb-3 text-muted">&copy; 2017-2018</small>
          </div>
          <div class="col-6 col-md">
            <h5>Exemplo de formato</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">formatação</a></li>

            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Resources</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Resource</a></li>
              <li><a class="text-muted" href="#">Resource name</a></li>
              <li><a class="text-muted" href="#">Another resource</a></li>
              <li><a class="text-muted" href="#">Final resource</a></li>
            </ul>
          </div>
          <div class="col-6 col-md">
            <h5>Sobre</h5>
            <ul class="list-unstyled text-small">
              <li><a class="text-muted" href="#">Time</a></li>
              <li><a class="text-muted" href="#">Localização</a></li>
              <li><a class="text-muted" href="#">Privacidade</a></li>
              <li><a class="text-muted" href="#">Termos</a></li>
            </ul>
          </div>
        </div>
      </footer>
    </div>
    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
  </body>
</html>