comprador/urls.py
from django.contrib import admin
from django.urls import include, path
from .views import PedidoView, ListagemView, PedidoView, CompradorCreateView, EstoqueCreateView, HomeView, PedidoUpdateEstoque, LitarPedidoCliente, LitarFornecedoresP, PedidoUpdateView
from .views import PedidoUpdatePPView

app_name = 'comprador'
urlpatterns = [
    path('pedido/', PedidoView.as_view(), name='p'),
    #path('pedido/', PedidoView.as_view(), name='p'),
    path('listagem/', ListagemView.as_view(), name='list'),
    path('comprador_cadastro/', CompradorCreateView.as_view(), name='create_comprador'),
    path('estoque_compredor/', EstoqueCreateView.as_view(), name='create_estoque'),
    path('home_compredor/', HomeView.as_view(), name='comprador_home'),
    path('receber_pedido/', PedidoUpdateEstoque.as_view(), name='comprador_listar_pedidos'),
    path('lista_pedido_comprador/', LitarPedidoCliente.as_view(), name='comprador_pedido_list'),
    path('litar_fornecedores_p/', LitarFornecedoresP.as_view(), name='litar_fornecedores_p'),

    path('finalizar_pedido/<int:pk>/', PedidoUpdateView.as_view(), name='finalizar_pedido_up'),
    path('chegou_pedido/<int:pk>/', PedidoUpdatePPView.as_view(), name='uppp')
]

maratona_ambev/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('siteprincipal.urls')),
    path('comprador/', include('comprador.urls')),
    path('distribuidor/', include('distribuidor.urls')),

]
#urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

matatona_ambev/matatona_ambev/urls.py
from django.contrib import admin
from django.urls import include, path
from django.conf.urls.static import static 
from django.conf import settings
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('siteprincipal.urls')),
    path('comprador/', include('comprador.urls')),

]
#urlpatterns += static(settings.MEDIA_URL,document_root = settings.MEDIA_ROOT)

comprador/models.py
from django.db import models
from distribuidor.models import EstoqueDistribuidor
# Create your models here.
from django.db import models
from distribuidor.models import Distribuidor
import os
from django.utils.translation import ugettext_lazy as _
#from brutils import cpf as valida_cpf, cnpj as valida_cnpj
from django.urls import reverse

# Create your models here.
class Comprador(models.Model):
    nome_comprador = models.CharField(max_length=30)
    lat = models.DecimalField(max_digits=8, decimal_places=6, verbose_name= 'Latitude')
    lon = models.DecimalField(max_digits=8, decimal_places=6, verbose_name= 'Longitude')
    tel_fixo = models.CharField(_('Telefone Fixo'), max_length=13, blank=True, null=True)
    tel_celular = models.CharField(_('Telefone Celular'), max_length=13, blank=True, null=True)
    cep = models.CharField(_('CEP'), max_length=10, blank=True, null=True)
    uf = models.CharField(_('UF'), max_length=2, blank=True, null=True)
    cidade = models.CharField(_('Cidade'), max_length=70, blank=True, null=True)
    bairro = models.CharField(_('Bairro'), max_length=70, blank=True, null=True)
    logradouro = models.CharField(_('Logradouro'), max_length=70, blank=True, null=True)
    numero = models.CharField(_('Número'), max_length=5, blank=True, null=True)
    complemento = models.CharField(_('Complemento'), max_length=70, blank=True, null=True)
    dt_cadastro = models.DateTimeField(_('Dt. Cadastro'), auto_now_add=True)
    email = models.EmailField(_('E-mail'), blank=True, null=True)
    
    def __str__(self):
        return self.nome_comprador
    

class EstoqueComprador(models.Model):
    comprador = models.ForeignKey(Comprador,on_delete=models.PROTECT)
    nome_produto = models.CharField(max_length=30) 
    quantidade_em_estoque = models.IntegerField(blank=True, null=True)

    def __str__(self):
        return self.nome_produto

class Pedido(models.Model):
    qual_seu_pedido = models.CharField(max_length=30)
    qual_quantidade_de_unidade = models.IntegerField()
    comprador = models.ForeignKey(Comprador,on_delete=models.PROTECT)
    distribuidor = models.ForeignKey(Distribuidor,on_delete=models.PROTECT,blank=True, null=True)
    entregue = models.BooleanField(default=False, blank=True, null=True)
    data_entrega = models.DateTimeField(blank=True, null=True)

    @property
    def get_absolutettt_url(self):
        return reverse('comprador:uppp', kwargs={'pk': self.pk})

    def __str__(self):
        return self.qual_seu_pedido


    def save(self, *args, **kwargs):
        #se pedido for finalizado
        if self.entregue == True :
            #pega o id de distribuidor
            objeto_distribuidor = self.distribuidor
            #pega o id de estoque utilizando o distribuidor
            objeto_estoque = EstoqueDistribuidor.objects.filter(distribuidor = objeto_distribuidor )
            #atualiza o valor no estoque de acordo com a quantidade do pedido
            quantidade = objeto_estoque.quantidade_em_estoque
            quantidade = quantidade - self.qual_quantidade_de_unidade
            objeto_estoque.update(quantidade_em_estoque = quantidade)
            #salva no models estoqueDistribuidor
            super(EstoqueDistribuidor,objeto_estoque).save(*args,**kwargs)      
        
        super(Pedido, self).save(*args, **kwargs)

comprador/forms.py
from django import forms
from comprador.models import Pedido


#class PedidoForm(forms.Form):
#    qual_seu_pedido = forms.CharField(label='Informe aqui o seu pedido', max_length=100)
#    qual_quantidade_de_unidade = forms.IntegerField(label='Informe aqui a quantidade de unidade')

class PedidoForm(forms.ModelForm):
    class Meta:
        model = Pedido
        exclude = ('entregue','data_entrega','distribuidor')

comprador/views.py
from django.shortcuts import render
from django.views.generic import ListView
# Create your views here.
from django.views.generic import TemplateView
from .forms import PedidoForm
from django.views.generic.edit import FormView, CreateView, UpdateView
from django.urls import reverse
from .models import Comprador, EstoqueComprador, Pedido
from distribuidor.models import Distribuidor, EstoqueDistribuidor
from django.urls import reverse

class PedidoView(TemplateView):
    template_name = "pedido.html"


class ListagemView(TemplateView):
    template_name = "lista_for.html"



class PedidoView(CreateView):
    model = Pedido
    template_name = "pedido.html"
    form_class = PedidoForm
    #success_url = 'http://127.0.0.1:8000/comprador/listagem/'
    success_url = 'comprador:litar_fornecedores_p'

    def form_valid(self, form):
        qual_seu_pedido = form.cleaned_data['qual_seu_pedido']
        qual_quantidade_de_unidade = form.cleaned_data['qual_quantidade_de_unidade']
        
        print(qual_seu_pedido)

        self.request.session['quantidade_pedido'] = qual_quantidade_de_unidade
        self.request.session['nome_pedido'] = qual_seu_pedido
        form.comprador = Comprador.objects.get(pk=1)
        #self.request.session['pedido'] = self
        #cheese_blog = Blog.objects.get(name="Cheddar Talk")
        #print(form)
        # This method is called when valid form data has been POSTed.
        # It should return an HttpResponse.
        #form.send_email()

        return super().form_valid(form)
    def get_initial(self):
        comprador = Comprador.objects.get(pk=1)

        return {'comprador': comprador}

    def get_success_url(self):
        self.request.session['pedido'] = self.object.pk
        
        return reverse(self.success_url)

class PedidoUpdateView(UpdateView):
    model = Pedido
    template_name = "pedido.html"
    form_class = PedidoForm
    #success_url = 'http://127.0.0.1:8000/comprador/listagem/'
    success_url = 'landpage:home'

    def get_object(self, queryset=None):
        slug = self.kwargs.get(self.slug_url_kwarg)
        try:
            obj = Pedido.objects.get(pk=self.request.session['pedido'])
            obj.distribuidor = Distribuidor.objects.get(pk=4)
        except:
            raise Http404("Pedido não localizado")
        return obj
    # def get_object(self, queryset=None):
    #     slug = self.kwargs.get(self.slug_url_kwarg)
    #     try:
    #         obj = ClientePF.objects.get(slug=slug, empresa=self.request.session['empresa'])
    #     except:
    #         raise Http404("Cliente não localizado")
    #     return obj


    def form_valid(self, form):

        return super().form_valid(form)

    def get_success_url(self):
        return reverse(self.success_url)




class PedidoUpdatePPView(UpdateView):
    model = Pedido
    template_name = "pedido.html"
    

    fields = ['qual_seu_pedido','qual_quantidade_de_unidade','comprador','distribuidor','entregue','data_entrega']

    #success_url = 'http://127.0.0.1:8000/comprador/listagem/'
    success_url = 'landpage:home'

    # def get_object(self, queryset=None):
    #     slug = self.kwargs.get(self.slug_url_kwarg)
    #     try:
    #         obj = Pedido.objects.get(pk=self.request.session['pedido'])
    #         obj.distribuidor = Distribuidor.objects.get(pk=4)
    #     except:
    #         raise Http404("Pedido não localizado")
    #     return obj
    # def get_object(self, queryset=None):
    #     slug = self.kwargs.get(self.slug_url_kwarg)
    #     try:
    #         obj = ClientePF.objects.get(slug=slug, empresa=self.request.session['empresa'])
    #     except:
    #         raise Http404("Cliente não localizado")
    #     return obj


    def form_valid(self, form):

        return super().form_valid(form)

    def get_success_url(self):
        return reverse(self.success_url)




class CompradorCreateView(CreateView):
    model = Comprador
    template_name = "comprador_form.html"
    fields = ['nome_comprador', 'email', 'tel_fixo','tel_celular','cep','cidade','lat','lon']
    success_url = 'landpage:home'

    def get_success_url(self):
        return reverse(self.success_url)


class EstoqueCreateView(CreateView):
    model = EstoqueComprador
    template_name = "estoque_form.html"
    fields = ['comprador', 'nome_produto', 'quantidade_em_estoque']
    success_url = 'comprador:p'

    def get_initial(self):
        comprador = Comprador.objects.get(pk=1)

        return {'comprador': comprador}

    def get_success_url(self):
        return reverse(self.success_url)


class EstoqueListView(CreateView):
    template_name = "estoque_list.html"


class HomeView(TemplateView):
    template_name = 'comprador_home.html'


#class PedidoCreateView(CreateView):
#    model = Pedido
#    form_class = ClientePFForm
#    template_name = 'fazer_pedido_form.html'  

#from django.shortcuts import redirect
class PedidoUpdateEstoque(UpdateView):
    model = Pedido
    template_name = 'receber_pedido_form.html'
#



class LitarPedidoCliente(ListView):
    model = Pedido
    template_name = 'cliente_list_pedido.html'


class LitarFornecedoresP(ListView):
    model = Distribuidor
    template_name = 'fornecedor_list_pedido.html'

    # def get_context_data(self, **kwargs):
    #     context = super(LitarFornecedoresP, self).get_context_data(**kwargs)
    #     if self.request.POST:
    #         context['Pedido'] = Pedido.objects.all()

    #     return context
    def get_queryset(self):
            estoque_distri = EstoqueDistribuidor.objects.filter(quantidade_em_estoque__gte=self.request.session['quantidade_pedido'],nome_produto__icontains=self.request.session['nome_pedido'])
            #self.request.session['quantidade_pedido'] = qual_quantidade_de_unidade
            #self.request.session['nome_pedido'] = qual_seu_pedido
            for i in estoque_distri:
                print(i.distribuidor)

            
            #palavra_chave = form.cleaned_data['palavra_chave']
            #tipo = form.cleaned_data['tipo']
            #situacao = form.cleaned_data['situacao']
            #categoria = form.cleaned_data['categoria']
            if self.request.GET:
                qs = super(LitarFornecedoresP, self).get_queryset().filter()
                t = estoque_distri
            else:
                qs = super(LitarFornecedoresP, self).get_queryset().filter()
                t = estoque_distri
            return t

comprador/templates/cliente_list_pedido.html
{% load static %}
{% extends 'core/layoutbase.html' %} 

{% block actions %}
{% endblock %}

{% block title %}
	Listagem de Pedidos Cliente
{% endblock %}


{% block content %}

<table class="table">
    
  <thead>
    <tr>
        <td>Pedido</td>
        <td>Quantidade</td>
        <td>Distribuidor</td>
        <td>Entregue</td>
        <td>Data da entrega</td>
        <td>Pedido foi entregue</td>
    </tr>
  </thead>
  {% for i in object_list %}
  <tbody>
    <tr>
        <td>{{ i.qual_seu_pedido }}</td>
        <td>{{ i.qual_quantidade_de_unidade }}</td>
        <td>{{ i.distribuidor }}</td>
        <td> {% if not i.entregue %}
                Não entregue
            {% else %}
                Entregue
            {% endif %}

        <td>{{ i.data_entrega|default_if_none:"Não entregue" }}</td>
        
        <td><a class="btn btn-primary" href="{{ i.get_absolutettt_url }}" role="button">Pedido Chegou</a></td>
        
    </tr>

  </tbody>
      {% endfor %}
</table>

{% endblock %}

comprador/templates/comprador_form.html
{% load static %}
{% extends 'core/layoutbase.html' %} 

{% block actions %}
{% endblock %}

{% block title %}
	Cadastro de comprador
{% endblock %}

{% block content %}
<div class="container">
        <h1>Tela cadastro Comprador</h1>
        
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input  class="btn btn-primary" type="submit" value="cadastrar">
            {% comment %} <a class="btn btn-primary" type="submit" href="{% url 'comprador:list' %}" role="button"></a> {% endcomment %}
        </form>
        
    </div>
{% endblock %}

comprador/templates/comprador_home.html
{% load static %}
{% extends 'core/layoutbase.html' %} 


{% block content  %}

    <div class="container">
        <h1>Tela do comprador</h1>
        <a class="btn btn-primary" href="{% url 'comprador:p' %}" role="button">Quero fazer um pedido</a>
        <a class="btn btn-primary" href="{% url 'comprador:create_comprador' %}" role="button">Cadastrar Comprador</a>
        <a class="btn btn-primary" href="{% url 'comprador:create_estoque' %}" role="button">criar estoque</a>
        

        <a class="btn btn-primary" href="{% url 'comprador:comprador_pedido_list' %}" role="button">Conferir pedido</a>
       
    </div>
{% endblock  %}

comprador/templates/estoque_form.html
{% load static %}
{% extends 'layoutbase.html' %} 

{% block actions %}
{% endblock %}

{% block title %}
	Cadastro do estoque
{% endblock %}

{% block content %}
<div class="container">
        <h1>Tela cadastro do estoque</h1>
        
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input  class="btn btn-primary" type="submit" value="cadastrar">
            {% comment %} <a class="btn btn-primary" type="submit" href="{% url 'comprador:list' %}" role="button"></a> {% endcomment %}
        </form>
        
    </div>
{% endblock %}

comprador/templates/fazer_pedido_form.html
{% load static %}
{% extends 'layoutbase.html' %} 

{% block actions %}
{% endblock %}

{% block title %}
	Fazer Pedido
{% endblock %}

{% block content %}
<div class="container">
        <h1>Fazer Pedido</h1>
        
        <form method="post">
        {% csrf_token %}
            {{ form.as_p }}
            <input class="btn btn-primary" type="submit" value="cadastrar">
            {% comment %} <a class="btn btn-primary" type="submit" href="{% url 'comprador:list' %}" role="button"></a> {% endcomment %}
        </form>
        
    </div>
{% endblock %}

comprador/templates/fornecedor_list_pedido.html
{% load static %}
{% extends 'core/layoutbase.html' %} 

{% block actions %}
{% endblock %}

{% block title %}
	Listagem de Pedidos Cliente
{% endblock %}


{% block content %}

<table class="table">
    
  <thead>
    <tr>
        <td>Nome do distribuidor</td>
        <td>Produto</td>
        <td>Quantidade em estoque</td>
        <td>Periodo De entrega</td>
        <td>finalizar pedido</td>
    </tr>
  </thead>
  {% for i in object_list %}
  <tbody>
    <tr>
        <td>{{ i.distribuidor.nome_distribuidor }}</td>
        <td>{{ i.nome_produto }}</td>
        <td>{{ i.quantidade_em_estoque }}</td>
        <td>{{ i.distribuidor.inicio_hora_entrega }} {{ i.distribuidor.fim_hora_entrega }}</td>
        <td><a class="btn btn-primary" type="submit" href="{{ i.get_absolute_url2 }}" role="button"></a></td>
    </tr>

  </tbody>
      {% endfor %}
</table>

{% endblock %}

comprador/templates/lista_for.html
{% load static %}
<!-- <!DOCTYPE html>
<html>
  <head>
    <title>Simple Map</title>
    <meta name="viewport" content="initial-scale=1.0">
    <meta charset="utf-8">
    <style>
      /* Always set the map height explicitly to define the size of the div
       * element that contains the map. */
      #map {
        height: 100%;
      }
      /* Optional: Makes the sample page fill the window. */
      html, body {
        height: 100%;
        margin: 0;
        padding: 0;
      }
    </style>
  </head>
  <body>
    <div id="map"></div>
    <script>
      var map;
      function initMap() {
        map = new google.maps.Map(document.getElementById('map'), {
          center: {lat: -29.691387, lng: -53.819597},
          zoom: 8
        });
      }
    </script>

    <script async defer
      src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwlRGyGUw2ypjQtHCZWY89JAIVHcBHI3U&callback=initMap">
    </script>
    
  </body>
</html> -->

<head>
  <meta name="viewport" content="initial-scale=1.0, user-scalable=no">
  <meta charset="utf-8">
  <title>Teste GoogleMaps API</title>
  <style>
    
    #map {
      height: 100%;
    }
    
    html, body {
      height: 100%;
      margin: 0;
      padding: 0;
    }
    
  </style>
</head>
<body>

  
  <div id="map"></div>
  <script async defer
  src="https://maps.googleapis.com/maps/api/js?key=AIzaSyAwlRGyGUw2ypjQtHCZWY89JAIVHcBHI3U&callback=initMap"></script> </script>
  </body>

<script>
function initMap() 
      {
        var directionsDisplay = new google.maps.DirectionsRenderer;
        
        /*
        --  MUDA A COR DA POLYLINE -> var directionsDisplay = new google.maps.DirectionsRenderer({ polylineOptions: { strokeColor: "blue" } });
        */
        
        var directionsService = new google.maps.DirectionsService;        
        var map = new google.maps.Map(document.getElementById('map'), {
          
          disableDefaultUI: true,
          zoom: 14,
          zoomControl: false,
          scaleControl: true,
          durationInTraffic: true,
          streetViewControl: true,
          suppressMarkers: true,

          center: {lat: -29.691387, lng: -53.819597}, // Paulista
        });
        
        directionsDisplay.setMap(map);
        calculateAndDisplayRoute(directionsService, directionsDisplay);
        
        //var trafficLayer = new google.maps.TrafficLayer();
        //trafficLayer.setMap(map);
    
        var noPoi = [
        {
            featureType: "poi",
            stylers: [
              { visibility: "on" }
            ]   
          }
        ];
        map.setOptions({styles: noPoi});
        
      }

      function calculateAndDisplayRoute(directionsService, directionsDisplay) {
        
        directionsService.route({
          origin: {lat: -29.68835101, lng: -53.81017685},  // Paulista inicia.
          destination: {lat: -29.69737283, lng: -53.79481316},  // Paulista final.
          travelMode: google.maps.DirectionsTravelMode.DRIVING
       
        },function(response, status) {
          
          if (status == google.maps.DirectionsStatus.OK) {
              directionsDisplay.setOptions({ preserveViewport: true });
              directionsDisplay.setDirections(response);
          } else {
            window.alert('Directions request failed due to ' + status);
          }
        });
      }
</script>

comprador/templates/pedido.html
{% load static %}
{% extends 'core/layoutbase.html' %} 


{% block content  %}

    <div class="container">
        <h1>Tela pedido</h1>
        
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input  class="btn btn-primary" type="submit" value="Quero fazer um pedido">
            {% comment %} <a class="btn btn-primary" type="submit" href="{% url 'comprador:list' %}" role="button"></a> {% endcomment %}
        </form>
        
    </div>
{% endblock  %}

comprador/templates/pedido_distribuidor_form.html
{% load static %}
{% extends 'core/layoutbase.html' %} 


{% block content  %}

    <div class="container">
        <h1>Tela pedido</h1>
        
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input  class="btn btn-primary" type="submit" value="Gravar">
            {% comment %} <a class="btn btn-primary" type="submit" href="{% url 'comprador:list' %}" role="button"></a> {% endcomment %}
        </form>
        
    </div>
{% endblock  %}

comprador/templates/receber_pedido_form.html
{% load static %}
{% extends 'layoutbase.html' %} 

{% block actions %}
{% endblock %}

{% block title %}
	Cadastro do estoque
{% endblock %}

{% block content %}
<div class="container">
        <h1>Recebi Pedido</h1>
        
        <form method="post">{% csrf_token %}
            {{ form.as_p }}
            <input  class="btn btn-primary" type="submit" value="cadastrar">
            {% comment %} <a class="btn btn-primary" type="submit" href="{% url 'comprador:list' %}" role="button"></a> {% endcomment %}
        </form>
        
    </div>
{% endblock %}